<a href="https://colab.research.google.com/github/nataliarufino/perceptron-linear-regression/blob/main/Tarefa_1_1_Redes_Rasas_Regress%C3%A3o_Linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tarefa Prática 1.1: Perceptron e Adaline  

### Regressão Linear:

* Ler o banco de dados hospital.xls
* Usar as características: sexo, idade peso, fumante/não fumante
* Fazer a previsão de pressão /máxima
* Utilizar validação cruzada de 5 pastas
* Calcular o erro médio quadrático e coeficiente de pearson para cada pasta
* Determinar o valor médio do coeficiente de Pearson e do erro médio quadrático

**Discente**
Natália de Sousa Rufino - 21951544

### Passos para a solução
1. Preparar os dados
2. Construir o modelo
3. Treinar o modelo
4. Avaliar o modelo

# Importing Libraries

*   Numpy - read/data manipulation
*   Pandas - read/data manipulation
*   Sklearn - separate data and train the model

In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split, KFold
from sklearn import metrics

# Preparing the data

1. Read the xls data
2. Show data


In [ ]:
data = pd.read_excel('/content/sample_data/hospital.xls')
data

ID   LastName     Sex  Age  Weight  Smoker  BloodPressure_1  \
0   YPL-320      SMITH    Male   38     176    True              124   
1   GLI-532    JOHNSON    Male   43     163   False              109   
2   PNI-258   WILLIAMS  Female   38     131   False              125   
3   MIJ-579      JONES  Female   40     133   False              117   
4   XLK-030      BROWN  Female   49     119   False              122   
..      ...        ...     ...  ...     ...     ...              ...   
95  REV-997  ALEXANDER    Male   25     171    True              128   
96  HVR-372    RUSSELL    Male   44     188    True              124   
97  MEZ-469    GRIFFIN    Male   49     186   False              119   
98  BEZ-311       DIAZ    Male   45     172    True              136   
99  ZZB-405      HAYES    Male   48     177   False              114   

    BloodPressure_2  Trials_1  Trials_2  Trials_3  Trials_4  
0                93      18.0       NaN       NaN       NaN  
1                77      11.0      13.0      22.0       NaN  
2                83       NaN       NaN       NaN       NaN  
3                75       6.0      12.0       NaN       NaN  
4                80      14.0      23.0       NaN       NaN  
..              ...       ...       ...       ...       ...  
95               99       1.0       NaN       NaN       NaN  
96               92      22.0       NaN       NaN       NaN  
97               74       9.0       NaN       NaN       NaN  
98               93       NaN       NaN       NaN       NaN  
99               86      28.0       NaN       NaN       NaN  

[100 rows x 12 columns]

3. Define the features (x):
* Sex
* Age
* Weight
* Smoker

In [ ]:
data.columns

Index(['ID', 'LastName', 'Sex', 'Age', 'Weight', 'Smoker', 'BloodPressure_1',
       'BloodPressure_2', 'Trials_1', 'Trials_2', 'Trials_3', 'Trials_4'],
      dtype='object')

In [ ]:
features = ['Sex', 'Age', 'Weight', 'Smoker']
len(features)

4

4. Define x as features and y as targets

In [ ]:
x = data[features].values # todas as variáveis desejadas
y = data['BloodPressure_1'].values # pressão máxima

In [ ]:
x

array([['Male', 38, 176, True],
       ['Male', 43, 163, False],
       ['Female', 38, 131, False],
       ['Female', 40, 133, False],
       ['Female', 49, 119, False],
       ['Female', 46, 142, False],
       ['Female', 33, 142, True],
       ['Male', 40, 180, False],
       ['Male', 28, 183, False],
       ['Female', 31, 132, False],
       ['Female', 45, 128, False],
       ['Female', 42, 137, False],
       ['Male', 25, 174, False],
       ['Male', 39, 202, True],
       ['Female', 36, 129, False],
       ['Male', 48, 181, True],
       ['Male', 32, 191, True],
       ['Female', 27, 131, True],
       ['Male', 37, 179, False],
       ['Male', 50, 172, False],
       ['Female', 48, 133, False],
       ['Female', 39, 117, False],
       ['Female', 41, 137, False],
       ['Female', 44, 146, True],
       ['Female', 28, 123, True],
       ['Male', 25, 189, False],
       ['Female', 39, 143, False],
       ['Female', 25, 114, False],
       ['Male', 36, 166, False],
       ['Male', 3

Como "Sex" e "Smoker" são strings e não dados numéricos

Pode-se considerar:

* Female = 0
* Male = 1
* Smoker = 1
* Non-smoker = 0

In [ ]:
xSex = np.where(x[:,0] == 'Male', 1, 0)
x[:,0] = xSex
x

array([[1, 38, 176, True],
       [1, 43, 163, False],
       [0, 38, 131, False],
       [0, 40, 133, False],
       [0, 49, 119, False],
       [0, 46, 142, False],
       [0, 33, 142, True],
       [1, 40, 180, False],
       [1, 28, 183, False],
       [0, 31, 132, False],
       [0, 45, 128, False],
       [0, 42, 137, False],
       [1, 25, 174, False],
       [1, 39, 202, True],
       [0, 36, 129, False],
       [1, 48, 181, True],
       [1, 32, 191, True],
       [0, 27, 131, True],
       [1, 37, 179, False],
       [1, 50, 172, False],
       [0, 48, 133, False],
       [0, 39, 117, False],
       [0, 41, 137, False],
       [0, 44, 146, True],
       [0, 28, 123, True],
       [1, 25, 189, False],
       [0, 39, 143, False],
       [0, 25, 114, False],
       [1, 36, 166, False],
       [1, 30, 186, True],
       [0, 45, 126, True],
       [0, 40, 137, False],
       [0, 25, 138, False],
       [1, 47, 187, False],
       [1, 44, 193, False],
       [0, 48, 137, False],
  

In [ ]:
xSmoker = np.where(x[:,3] == True, 1, 0)
x[:,3] = xSmoker
x

array([[1, 38, 176, 1],
       [1, 43, 163, 0],
       [0, 38, 131, 0],
       [0, 40, 133, 0],
       [0, 49, 119, 0],
       [0, 46, 142, 0],
       [0, 33, 142, 1],
       [1, 40, 180, 0],
       [1, 28, 183, 0],
       [0, 31, 132, 0],
       [0, 45, 128, 0],
       [0, 42, 137, 0],
       [1, 25, 174, 0],
       [1, 39, 202, 1],
       [0, 36, 129, 0],
       [1, 48, 181, 1],
       [1, 32, 191, 1],
       [0, 27, 131, 1],
       [1, 37, 179, 0],
       [1, 50, 172, 0],
       [0, 48, 133, 0],
       [0, 39, 117, 0],
       [0, 41, 137, 0],
       [0, 44, 146, 1],
       [0, 28, 123, 1],
       [1, 25, 189, 0],
       [0, 39, 143, 0],
       [0, 25, 114, 0],
       [1, 36, 166, 0],
       [1, 30, 186, 1],
       [0, 45, 126, 1],
       [0, 40, 137, 0],
       [0, 25, 138, 0],
       [1, 47, 187, 0],
       [1, 44, 193, 0],
       [0, 48, 137, 0],
       [1, 44, 192, 1],
       [0, 35, 118, 0],
       [1, 33, 180, 1],
       [0, 38, 128, 0],
       [1, 39, 164, 1],
       [1, 44, 1

In [ ]:
y # para verificar se o y está retornando os valores corretos

array([124, 109, 125, 117, 122, 121, 130, 115, 115, 118, 114, 115, 127,
       130, 114, 130, 124, 123, 119, 125, 121, 123, 114, 128, 129, 114,
       113, 125, 120, 127, 134, 121, 115, 127, 121, 127, 136, 117, 124,
       120, 128, 116, 132, 137, 117, 116, 119, 123, 116, 124, 129, 130,
       132, 117, 129, 118, 120, 138, 117, 113, 122, 115, 120, 117, 123,
       123, 119, 110, 121, 138, 125, 122, 120, 117, 125, 124, 121, 118,
       120, 118, 118, 122, 134, 131, 113, 125, 135, 128, 123, 122, 138,
       124, 130, 123, 129, 128, 124, 119, 136, 114])

In [ ]:
x.shape

(100, 4)

In [ ]:
y.shape

(100,)

5. Use `train_test_split` to divide the data in 80/20

Nesse caso,
20% das amostras para teste e os outros 80% para treinamento

In [ ]:
x_train, x_test, y_train, y_teste = train_test_split(x, y, test_size=0.2, random_state=4)

In [ ]:
x_train.shape

(80, 4)

In [ ]:
x_test.shape

(20, 4)

# Building the model

1. Using `LinearRegression()` to build the model

In [ ]:
model = LinearRegression()

# Training/Evaluating the model


Para avaliar o modelo, o enunciado pede a validação cruzada em 5 pastas

In [ ]:
kf = KFold(n_splits = 5, shuffle=False)
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [ ]:
for i, j in kf.split(x):
  print(i)
  print(j)
  print("\n")

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67
 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91
 92 93 94 95 96 97 98 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67
 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91
 92 93 94 95 96 97 98 99]
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 60 61 62 63 64 65 66 67
 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91
 92 93 94 95 96 97 98 99]
[40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23


In [ ]:
x_train

array([[1, 34, 186, 0],
       [0, 49, 119, 0],
       [1, 39, 188, 0],
       [0, 35, 131, 0],
       [1, 39, 182, 1],
       [0, 29, 130, 0],
       [0, 46, 142, 0],
       [1, 25, 186, 0],
       [0, 40, 127, 1],
       [1, 50, 172, 0],
       [1, 36, 189, 0],
       [0, 30, 141, 0],
       [0, 25, 114, 0],
       [1, 31, 178, 1],
       [0, 28, 127, 0],
       [1, 42, 194, 0],
       [1, 37, 179, 0],
       [0, 31, 141, 1],
       [1, 40, 180, 0],
       [0, 38, 128, 0],
       [0, 33, 142, 1],
       [1, 32, 183, 0],
       [0, 42, 137, 0],
       [0, 38, 130, 0],
       [0, 41, 137, 0],
       [0, 48, 134, 0],
       [0, 44, 146, 1],
       [1, 25, 174, 0],
       [0, 30, 124, 0],
       [1, 25, 189, 0],
       [0, 29, 120, 0],
       [1, 42, 158, 0],
       [0, 27, 131, 1],
       [0, 31, 130, 0],
       [0, 40, 137, 0],
       [1, 44, 193, 0],
       [1, 48, 181, 1],
       [0, 44, 136, 1],
       [0, 37, 120, 1],
       [1, 28, 189, 1],
       [1, 36, 166, 0],
       [0, 29, 1

Cálculo do erro médio quadrático e coeficiente de pearson para cada pasta

In [ ]:
i = 0

mse_average = 0
r_average = 0

# Cáculo de MSE e coeficiente de Pearson para cada pasta
for train_index, test_index in kf.split(x):
  x_train = x[train_index, :]
  x_test = x[test_index, :]

  y_train = y[train_index]
  y_test = y[test_index]

  model.fit(x_train, y_train) # para treinar o modelo
  y_pred = model.predict(x_test)  # predict() para previsões
  mse_ = metrics.mean_squared_error(y_test, y_pred) # para mostrar MSE
  r = np.corrcoef(y_pred, y_test) # para calcular o coeficiente de Pearson

  i+=1

  print("\n\n================== Fold " + str(i) + " ==================")
  print(len(x_train), len(y_train))
  print(len(x_test), len(y_test))
  print("Model Coeficient: ", model.coef_)  # mostra o viés
  print("Model Intercept: ", model.intercept_)  # mostra pesos
  print("MSE: {} ".format(mse_))
  print("Coeficiente de Pearson:\n {} ".format(r))

  mse_average = mse_average + mse_
  r_average = r_average + r



================== Fold 1 ==================
80 80
20 20
Model Coeficient:  [ 1.6658943   0.09282703 -0.03113033  9.97764216]
Model Intercept:  120.22461458105191
MSE: 24.44567558971206 
Coeficiente de Pearson:
 [[1.         0.64979733]
 [0.64979733 1.        ]] 


================== Fold 2 ==================
80 80
20 20
Model Coeficient:  [-0.3305332   0.02802309  0.01005945  9.9393059 ]
Model Intercept:  116.82424976207196
MSE: 19.16836426362937 
Coeficiente de Pearson:
 [[1.         0.72490823]
 [0.72490823 1.        ]] 


================== Fold 3 ==================
80 80
20 20
Model Coeficient:  [ 1.80100359  0.10051847 -0.03228915  9.04301332]
Model Intercept:  120.14329720222923
MSE: 16.65318666696897 
Coeficiente de Pearson:
 [[1.         0.88161462]
 [0.88161462 1.        ]] 


================== Fold 4 ==================
80 80
20 20
Model Coeficient:  [ 2.71012735  0.0904549  -0.06516558 10.48408207]
Model Intercept:  124.5649063678913
MSE: 21.10773554857101 
Coeficiente de

Cálculo do valor médio do coeficiente de Person e erro médio quadrático

In [ ]:
mse_average = mse_average/5
r_average = r_average/5

print("Valor médio do coeficiente de Pearson e do MSE \n")
print("Média do coeficiente de Person: \n {} \n".format(r_average))
print("Média do MSE: {}".format(mse_average))

Valor médio do coeficiente de Pearson e do MSE 

Média do coeficiente de Person: 
 [[1.         0.67086233]
 [0.67086233 1.        ]] 

Média do MSE: 24.39156820186144


O MSE calcula a diferença entre o valor predito e o real. Quanto menor é o valor de MSE, melhor o modela performa em relação as previsões

A correlação de Pearson quantifica o grau de relacionamento entre duas variáveis contínuas, seu valor varia de -1 a 1.
1 indica correlação perfeita positiva e -1 correlação perfeita negativa

**A pasta 3** é a que apresenta *menor MSE* e *correlação de Pearson mais próxima de 1*, por isso o seu modelo é o escolhido para teste e predições neste caso


In [ ]:
y_pred

array([118.76969295, 119.4166478 , 128.06555237, 117.39818865,
       118.07712429, 129.18193683, 128.27398838, 129.77821957,
       128.12762847, 118.58946677, 129.1171598 , 119.93992236,
       117.62450053, 120.10733098, 120.02892093, 127.22508188,
       129.93658158, 120.54902266, 129.62444397, 120.1880984 ])

Selecionando o modelo 3

In [ ]:
i = 0
for train_index, test_index in kf.split(x):
  if i == 2:
    x_train = x[train_index, :]
    x_test = x[test_index, :]

    y_train = y[train_index]
    y_test = y[test_index]

  i+=1

In [ ]:
model.fit(x_train, y_train)

LinearRegression()

In [ ]:
y_pred = model.predict(x_test)
y_pred

array([129.61211365, 120.45819881, 129.95326024, 128.44240221,
       120.91389793, 119.50344517, 119.08322942, 120.15653021,
       121.06439064, 129.4293318 , 130.42356342, 129.21779861,
       129.1495693 , 120.12116004, 130.00745548, 119.95914429,
       119.93780819, 130.02148955, 119.75091853, 119.76540939])

Mostrar o y_test e y_pred para verificar o quão bem o modelo está perfomando

In [ ]:
y_pred[18]

119.75091852661961

In [ ]:
y_test[18]

117

# Testing the model

Usando os valores abaixo para fazer uma nova predição:
* Sex: Male (0)
* Age: 53
* Weight: 198
* Smoker: 0 (non-smoker)

In [ ]:
x_new = np.array([0, 53, 198, 0])
x_new

array([  0,  53, 198,   0])

In [ ]:
y_new = model.predict([x_new])
y_new

array([119.07752417])

* Sex: Female (1)
* Age: 24
* Weight: 116
* Smoker: 0 (non-smoker)

In [ ]:
x_new = np.array([1, 24, 116, 0])
x_new

array([  1,  24, 116,   0])

In [ ]:
y_new = model.predict([x_new])
y_new

array([120.61120255])